service: default 
runtime: python39
instance_class: B8
basic_scaling:
  max_instances: 2
  idle_timeout: 10m

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301


entrypoint: gunicorn -b 0.0.0.0:8080  --worker-class gevent --threads 8 -t 100  --chdir app incident_dashboard:server




